src/app.ts

Output looks something like this now:
```ts
interface CourseWorkResource {
...
patch(request: PatchCourseWorkResourceRequest): Request<CourseWork>;
patch(
request: Omit<PatchCourseWorkResourceRequest, 'resource'>,
resource: PatchCourseWorkResourceRequest['resource'],
): Request<CourseWork>;
}
...
interface PatchCourseWorkResourceRequest {
/** V1 error format. */
"$.xgafv"?: string;
/** OAuth access token. */
access_token?: string;
/** Data format for response. */
alt?: string;
...
/** Request body */
resource: CourseWork;
}
```

De-deduplicate request types by extracting request type into separate interface

---

package-lock.json
package.json
src/app.ts

[form-data provides its own type definitions, so you don't need @types/form-data installed](https://www.npmjs.com/package/@types/form-data)
And it seems like we're not using it at all.

Remove @types/form-data dependecy

---

src/app.ts

Log JSON parsing errors

---

README.md
src/app.ts
src/cli.ts

Relates to https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/41
via:
```
npm run fix
```

Invoke prettier

---

src/app.ts

Include API revision number

---

tsconfig.json

Included tests in tsconfig to compile (`npm run tsc`) and check them using gts (`npm run check`)

Add tests to tsconfig

---

package.json

npm update

---

src/app.ts

As mentioned in #93 we won't support Apigee for now because it breaks our build and there's no good reason to fix it.

Ignore Apigee

---

src/app.ts

Closes #91
Added better error handling, so that the next time the issue will occur - we'll have better logs for debugging the root cause.

Better error handling for request()

---

bin/auto-update/git.ts
bin/auto-update/gitHelpers.ts
bin/auto-update/index.ts

Fixes #124 
This was actually original design (and that's why I used `git checkout -B` instead of `git checkout -b`, but I forgot about this :)
Not everything should be in order, tested on dummy DT fork.

Create or reset branches

---

bin/auto-update/git.ts
bin/auto-update/gitHelpers.ts
bin/auto-update/helpers.ts
bin/auto-update/index.ts

Compare branches diff only for type folder

---

src/app.ts

Handle "no documentationLink" case

---

bin/auto-update/gitHelpers.ts
bin/auto-update/index.ts

PR template update

---

README.md
package-lock.json
package.json
src/app.ts
src/cli.ts

Add proxy support for generator

---

src/app.ts

Properly handle "no documentationLink" case

---

src/app.ts

replace Record with its implementation

---

src/template/readme.dot

readme template fix

---

package-lock.json
package.json
src/app.ts
src/cli.ts
src/utils.ts

Replace asterisk with asterisk operator; read max-line-length from dtslint.json
Fixes https://github.com/Maxim-Mazurok/google-api-typings-generator/issues/277

Fix max line length

---

.editorconfig
src/app.ts
src/cli.ts

Add more type owners

---

.vscode/settings.json
bin/auto-update/git.ts
bin/auto-update/gitHelpers.ts
bin/auto-update/helpers.ts
bin/auto-update/index.ts
package-lock.json
package.json

Closes #320 
We have to find a way to not update DT fork branches for types that have open PRs.

[WIP] Don't update open PRs

---

bin/auto-update/helpers.ts

DT test command was [changed](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47282) from `test` to `test-all`

Update DT test command

---

bin/auto-update/git.ts
bin/auto-update/gitHelpers.ts
bin/auto-update/helpers.ts
bin/auto-update/index.ts
tests/gitHelpers.spec.ts

Closes #245
I approve bot PRs and comment "Ready to merge"

Auto merge PRs

---

.vscode/settings.json
bin/auto-update/gitHelpers.ts
bin/auto-update/index.ts

Add timeout after push

---

bin/auto-update/config.ts

Add gapi.client.analytics

---

src/app.ts
src/tslint.ts

Fix tslint ignore

---

.eslintrc.json
.vscode/settings.json
package-lock.json
package.json
src/app.ts
src/dt/app.ts
src/utils.ts

Request -> got, other minor fixes

---

.eslintrc.json
.vscode/settings.json
bin/auto-publish/git.ts
package-lock.json
package.json

downloadTarballArchive + deprecation check eslint

---

bin/lint.ts

Fix artifact upload failed type

---

README.md
package.json

Closes https://github.com/Maxim-Mazurok/google-api-typings-generator/issues/483

Add troubleshooting guide for 404 error

---

.github/workflows/codeql-analysis.yml
.vscode/settings.json

Update CodeQL workflow

---

.github/workflows/codeql-analysis.yml

CodeQL and Dependabot fix

---

bin/apis-sync-helper.ts
bin/auto-publish/git.ts
bin/auto-publish/helpers.ts
bin/auto-publish/index.ts
bin/get-latest-types.ts
src/dt/app.ts
src/dt/cli.ts

add .js to all

---

.github/dependabot.yml
.kodiak.toml
.vscode/extensions.json

Fix kodiak (add label, approve PRs)

---

.github/dependabot.yml
.kodiak.toml

rm automerge-kodiak label

---

.github/workflows/rebase-pull-requests.yml

Resolve conflict rebase (use gha-auto-dependabot-rebase action)

---

.github/workflows/auto-generate.yml
.github/workflows/auto-publish.yml
.github/workflows/ci-test.yml
.github/workflows/codeql-analysis.yml
.github/workflows/npm-dedupe-update.yml

Updated actions/checkout v2 to v3
Updated actions/setup-node v2 to v3
Closes #693 and closes #694

 Update actions/checkout and actions/setup-node v2 to v3

---

.github/workflows/auto-generate.yml
.github/workflows/auto-publish.yml
.github/workflows/ci-test.yml
.github/workflows/codeql-analysis.yml
.github/workflows/npm-dedupe-update.yml

Updated actions/checkout v2 to v3
Closes #694

 Update actions/checkout v2 to v3

---

.github/workflows/codeql-analysis.yml

Migrate CodeQL Action from v1 to v2

---

.github/workflows/auto-generate.yml
.github/workflows/auto-publish.yml
.github/workflows/ci-test.yml
.github/workflows/npm-dedupe-update.yml

Use node-version-file in actions/setup-node

---

.github/dependabot.yml

Keep GitHub actions up to date with Dependabot

---

src/app.ts
src/discovery.ts
src/dt/app.ts

Attempt to solve https://github.com/Maxim-Mazurok/google-api-typings-generator/actions/runs/5862528678/job/15894460191 and similar

relax request fails
